### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by Salvakiya** [alexander-smoktal/maul#1]
I was wondering what the state of the project was? I ran tests and got the following.
```
test test::expressions::test_expression::test_exp_prefix ... FAILED
test test::expressions::test_function::test_funcall_nested ... FAILED
test test::expressions::test_function::test_funcall_sample ... FAILED
test test::expressions::test_variables::test_var_name_resolution ... FAILED

**Comment by alexander-smoktal** [comment]
@Salvakiya , hi.
Sorry, didn't see the issue. Currently it's only lexer and parser.
It's my pet project primarily to practice Rust. I not always have time to work on it.
